### ISSUE TITLE
Add get involved to home page

### ISSUE THREAD

**Issue by SahityaRaipura** [build-umass/entrepreneurship-club#10]
Add get involved under what we do. "join our slack +slack logo" clicking slack logo should redirect to their slack.
https://docs.google.com/document/d/15_OxcwfChxP71mXCf65FluM3KPzi_1-mp-hA9_y6uAo/edit

**Comment by jtanniru** [comment]
I made edits to the landing page on my branch and added the get involved section under what we do. Under the get involved section, I added the slack link to the logo. Please check to make sure this was what was expected and the slack link was the correct one.
