### ISSUE TITLE
Create about page + move our team there

### ISSUE THREAD

**Issue by SahityaRaipura** [build-umass/entrepreneurship-club#12]
Move our team to about page and add about page.
https://docs.google.com/document/d/15_OxcwfChxP71mXCf65FluM3KPzi_1-mp-hA9_y6uAo/edit

**Comment by AVS1508** [comment]
## Status
Created initial pull request from _dev-about-page_ branch to _dev_ branch.

## Views
#### Home (Landing Page)
![Current Homepage](https://raw.githubusercontent.com/build-umass/entrepreneurship-club/dev-about-page/src/assets/img/theme/Home.png)
---
#### About Page
![About Page](https://raw.githubusercontent.com/build-umass/entrepreneurship-club/dev-about-page/src/assets/img/theme/About-Page.png)
---
#### Base Template
![Base Template](https://raw.githubusercontent.com/build-umass/entrepreneurship-club/dev-about-page/src/assets/img/theme/Base-Template.png)
---
